# Generated by Django 4.0 on 2022-01-06 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.basemodel')),
                ('article_title', models.CharField(max_length=100, unique=True)),
                ('article_subtitle', models.CharField(max_length=100, unique=True)),
                ('article_main_img', models.ImageField(upload_to='article_images')),
                ('article_text', models.TextField(max_length=300, verbose_name='Text Article')),
            ],
            bases=('article.basemodel',),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.basemodel')),
                ('article_to_like', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article', verbose_name='Article for like')),
            ],
            bases=('article.basemodel',),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.basemodel')),
                ('comment_text', models.TextField(max_length=300, verbose_name='Comment text')),
                ('article_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article', verbose_name='Article for comment')),
            ],
            bases=('article.basemodel',),
        ),
    ]
