# Generated by Django 4.0 on 2022-02-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_userprofile_avatar_alter_userprofile_bio_and_more'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorNotification',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basemodel')),
                ('status', models.CharField(blank=True, choices=[('N', 'Новая'), ('A', 'Назначена'), ('U', 'На рассмотрении'), ('R', 'Рассмотрена')], max_length=1, null=True, verbose_name='Статус')),
                ('comment_initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_initiator', to='mainapp.articlecomment', verbose_name='Comment initiator')),
                ('responsible_moderator', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_moderator', to='authapp.user', verbose_name='Responsible moderator')),
            ],
            options={
                'db_table': 'moderator_notification',
                'ordering': ['-created_timestamp'],
            },
            bases=('mainapp.basemodel',),
        ),
    ]
