# Generated by Django 4.0 on 2022-02-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='mainapp.article', verbose_name='Article for comment'),
        ),
    ]
