# Generated by Django 4.0 on 2022-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_moderatornotification_responsible_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatornotification',
            name='status',
            field=models.CharField(choices=[('N', 'Новая'), ('A', 'Назначена'), ('U', 'На рассмотрении'), ('R', 'Рассмотрена')], default='N', max_length=1, verbose_name='Статус'),
        ),
    ]
