# Generated by Django 4.0 on 2022-02-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_userprofile_avatar_alter_userprofile_bio_and_more'),
        ('mainapp', '0004_alter_moderatornotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatornotification',
            name='responsible_moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_moderator', to='authapp.user', verbose_name='Responsible moderator'),
        ),
    ]
