# Generated by Django 4.0 on 2022-01-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='like_author', to='authapp.user', verbose_name='Like Author'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article_to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_comment', to='articleapp.article', verbose_name='Article for comment'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_author', to='authapp.user', verbose_name='Comment Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_author', to='authapp.user', verbose_name='Author article'),
        ),
    ]
