# Generated by Django 4.0 on 2022-02-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_userprofile_avatar_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, verbose_name='password'),
        ),
    ]
