# Generated by Django 4.0 on 2022-02-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_date_end_banned_user_is_banned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUsersAboutBlocking',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authapp.basemodel')),
                ('moderator_who_blocked', models.UUIDField(verbose_name='кем заблокирован')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user', verbose_name='кто заблокирован')),
            ],
            bases=('authapp.basemodel',),
        ),
    ]
