# Generated by Django 4.0 on 2022-02-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_notificationusersaboutblocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationusersaboutblocking',
            name='message',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='дата снятия блокировки'),
        ),
    ]
